version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: Mypassword1234
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  mycontainer:
    build: .
    ports:
      - "80:80"
    depends_on:
      - db
volumes:
  db-data: