version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: Mypassword1234
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  admin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: Mypassword1234
    ports:
      - 8080:80
    volumes:
      - admin-data:/var/lib/pgadmin
  mycontainer:
    build: .
    ports:
      - "80:80"
    depends_on:
      - db
    volumes:
      - ./app:/code/app
volumes:
  db-data:
  admin-data: